### ISSUE TITLE
Thing

### ISSUE THREAD

**Issue by Shybella** [Charles445/RLTweaker#1]
https://www.youtube.com/watch?v=2DMuIHdPyNg

Couldn't find your discord, wanted this in a PM, could something be done about this? I will pay for your time.

**Comment by Charles445** [comment]
Here's the patch I wrote a bit ago to tackle this that's been circulated recently. 
Hopefully someone sent it to you by now, but if they didn't, I've attached it here in the zip.
Just grab the jar and put it on the server. If you run into any further trouble, please let me know.
(also no payment please)
[lycanitesdupepatch-1.0.zip](https://github.com/Charles445/RLTweaker/files/5177384/lycanitesdupepatch-1.0.zip)
