### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by AzureDoom** [Charles445/RLTweaker#11]
Hi! I work for BisectHosting doing support tickets and we have been receiving a sharp increase of tickets from this mod in the RLCraft servers. It has been causing a ton of Out of Memory errors on servers ranging from 5GB to 10GB+. 

Crash log here: https://gist.github.com/AzureDoom/906b92d9d7dd3aa8246b371e35362542
It looks to be pointing to https://github.com/Charles445/RLTweaker/blob/master/src/main/java/com/charles445/rltweaker/handler/MinecraftHandler.java#L251 as the cause.

**Comment by Charles445** [comment]
I believe this is a situation in which the game generated a Mineshaft with an invalid bounding box, causing the Mineshaft.dat cleanup to check to see if it's loaded, and there isn't a proper fail-safe in place for invalid, massive structures.

A quick fix for affected servers is to delete the Mineshaft.dat files in their world folders.
I'm going to try and patch this in an update today, but if you need a more long term fix immediately, set the rltweaker config "Cleanup Worldgen Files" to false. That'll stop the mod from trying to clean up the Mineshaft.dat file entirely.

**Comment by Charles445** [comment]
Okay, this should do it

RLTweaker 0.5.3
https://www.curseforge.com/minecraft/mc-mods/rltweaker/files/3846836

No need to change any configs
Try updating an affected server with this and see if it resolves the issue

**Comment by AzureDoom** [comment]
Thank you very much! I will have anyone that runs into this issue try ASAP for you!

**Comment by AzureDoom** [comment]
Just reporting in that this new version has fixed the issues it seems!

**Comment by Charles445** [comment]
Great!
