### ISSUE TITLE
“RLTweaker” makes the mod “Ruins ” 'command ---RUINSTARIGGER  dont work when it is used in command_block 

### ISSUE THREAD

**Issue by MiracleBelief** [Charles445/RLTweaker#12]
Minecraft: 1.12.2
Forge: 14.23.5.2860
RLTweaker：1.12.2-0.5.3
Ruins : uploaded Jun 7, 2019 
Description: 
I use Ruins ( Structure Spawning System )'s templates( download http://greywolf.critter.net/minecraft.htm ) ,then i found  the Command Blocks in it all does not work. They were supposed to generate something then disappear.
LAST:
Thank you for your contribution.  This mod really makes my gaming experience better.

**Comment by Charles445** [comment]
In config/rltweaker.cfg, look for
"Remove RUINSTRIGGER Functionality"
Set that to false, and restart the game, it should start working again

**Comment by MiracleBelief** [comment]
Thank you very much.
