### ISSUE TITLE
Crash on startup: Couldn't find getEntitiesInAABBexcluding or func_175674_a

### ISSUE THREAD

**Issue by CalaMariGold** [Charles445/RLTweaker#14]
Hiya, I added RLTweaker to my modpack and came across this crash. I wasn't able to narrow down a mod incompatibility but I provided the entire latest.log here.

https://mclo.gs/Psf2DHp

Thanks!

**Comment by Charles445** [comment]
Looks like you have two RLTweaker versions installed

RLTweaker-1.12.2-0.5.12.jar (RLTweaker2)
and
RLTweaker-1.12.2-0.5.3.jar (RLTweaker)

I recommend removing RLTweaker and keeping RLTweaker2

**Comment by CalaMariGold** [comment]
Ah sorry about that. For some reason I was under the impression that rltweaker2 was an addon, but in hindsight it's obvious that it's a fork/continuation. Thanks!
